### ISSUE TITLE
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PodsMeta::save_taxonomy()

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5053]
**Describe the bug**

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PodsMeta::save_taxonomy(), 2 passed in /wp-includes/class-wp-hook.php on line 286 and exactly 3 expected in /wp-content/plugins/pods/classes/PodsMeta.php:1716, referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
Stack trace:, referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
#0 /wp-includes/class-wp-hook.php(286): PodsMeta->save_taxonomy(2173, 2173), referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
#1 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array), referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
#2 /wp-includes/plugin.php(453): WP_Hook->do_action(Array), referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
#3 /wp-includes/taxonomy.php(2197): do_action('create_term', 2173, 2173), referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
#4 /wp-includes/taxonomy.php(2290): wp_insert_term('...', 'term'), referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
#5 /wp-includes/post.php(4025): wp_set_object_terms(33980, Array, 'term', false), referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
#6 /var/www/vhosts/ in /wp-content/plugins/pods/classes/PodsMeta.php on line 1716, referer: https://www.your.domain/wp-admin/post.php?post=33980&action=edit
```

<details>
<summary>WordPress Environment</summary>
WordPress Version: 4.9.6

PHP Version: 7.2.6

MySQL Version: 5.5.55

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

Session Save Path: /var/lib/php/session

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: Yes
WPDB Prefix: wpk01_16_

WP Multisite Mode: Yes

WP Memory Limit: 64M

Pods Network-Wide Activated: No

Pods Install Location: /var/www/vhosts/wpm01.keraweb.nl/httpdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No
</details>

**Comment by sc0ttkclark** [comment]
Was the taxonomy pod named "term"?

**Comment by JoryHogeveen** [comment]
Nope, in this case it was `article_category`, a custom tax created with Pods.
I believe this is an AJAX error since I never noticed it until I saw it in the error logs.

**Comment by sc0ttkclark** [comment]
create_term action always passes three arguments, not sure why this would occur.
