### ISSUE TITLE
Class 'PodsMeta' not found when calling wp_delete_attachment

### ISSUE THREAD

**Issue by tomlschmidt** [pods-framework/pods#5931]
**Describe the bug**

I am trying to delete a bunch of images from the media library using the [wp_delete_attachment](https://developer.wordpress.org/reference/functions/wp_delete_attachment/) function provided by WordPress. It stops at the first image, stating that it cant find the class 'PodsMeta' at [pods/classes/PodsInit.php:2031](https://github.com/pods-framework/pods/blob/e4d6bf2abd0996125e40e7f7f0d13c82d53a6338/classes/PodsInit.php#L2031)

**To Reproduce**
1. Execute the following function in code: `wp_delete_attachment( [any media post id], true );`
4. See PHP Fatal error:  `Uncaught Error: Class 'PodsMeta' not found in pods/classes/PodsInit.php:2031`

**Expected behavior**
The image image with the corresponding id should be deleted from the media library.

## Pods Version
2.7.26

## WordPress Environment

<details>

WordPress Version: 5.5.3

PHP Version: 7.2.13

MySQL Version: 5.5.5

Server Software: Apache/2.4.37 (Win32) OpenSSL/1.0.2p PHP/7.2.13

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36

Session Save Path: \xampp\tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 62.086M

Current Memory Usage (real): 6.000M

Pods Network-Wide Activated: No

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Twenty

Currently Active Plugins:

Add From Server: 3.3.3
Gutenberg Ramp: 1.1.0
MSCG Collection: 1.0.0
Pods - Custom Content Types and Fields: 2.7.26
Query Monitor: 3.6.7
Regenerate Thumbnails: 3.1.4
WordPress Importer: 0.7
WordPress Import Export: 1.0
WPML Media: 2.5.5
WPML Multilingual CMS: 4.3.10
WPML String Translation: 3.0.7
WPML Translation Management: 2.9.5

</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.26","build":1612192054},"pods":{"69":{"id":69,"name":"artist","label":"Artists","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"firstname":{"id":70,"name":"firstname","label":"Firstname","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"lastname":{"id":71,"name":"lastname","label":"Lastname","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"artworks":{"id":8643,"name":"artworks","label":"Artworks","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"post_type","pick_val":"artwork","sister_id":"78","required":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"list","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"1","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"silverstripe_artist_id":{"id":100,"name":"silverstripe_artist_id","label":"silverstripe_artist_id","description":"","help":"","class":"","type":"text","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"silverstripe_title":{"id":5042,"name":"silverstripe_title","label":"silverstripe_title","description":"","help":"","class":"","type":"text","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""}},"show_in_menu":"1","label_singular":"Artist","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"page","capability_type_custom":"artwork","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_translation_priority":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"custom","rest_enable":"1","read_all":"0","write_all":"0","built_in_taxonomies_photographer":"0","pfat_filter_archive_custom":"the_content"},"74":{"id":74,"name":"artwork","label":"Artworks","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"year":{"id":75,"name":"year","label":"Year","description":"Year of creation","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":0,"text_placeholder":""},"inventory_number":{"id":76,"name":"inventory_number","label":"Inventory Number","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"availability":{"id":77,"name":"availability","label":"Availability","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"exhibition|ausgestellt\nstorage|nicht ausgestellt\ntravel|auf Reisen","required":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"artist":{"id":78,"name":"artist","label":"Artist","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"post_type","pick_val":"artist","sister_id":"8643","required":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"description":{"id":114,"name":"description","label":"Description","description":"","help":"","class":"","type":"wysiwyg","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_editor_height":"","wysiwyg_allowed_html_tags":""},"long_description":{"id":115,"name":"long_description","label":"Long Description","description":"","help":"","class":"","type":"wysiwyg","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_editor_height":"","wysiwyg_allowed_html_tags":""},"views":{"id":8646,"name":"views","label":"Views","description":"","help":"","class":"","type":"pick","weight":6,"pick_object":"media","pick_val":"","sister_id":"6150","required":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"1","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"list","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"silverstripe_artist_id":{"id":1154,"name":"silverstripe_artist_id","label":"silverstripe_artist_id","description":"","help":"","class":"","type":"text","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"silverstripe_artwork_id":{"id":1155,"name":"silverstripe_artwork_id","label":"silverstripe_artwork_id","description":"","help":"","class":"","type":"text","weight":8,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"silverstripe_title":{"id":5041,"name":"silverstripe_title","label":"silverstripe_title","description":"","help":"","class":"","type":"text","weight":9,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"silverstripe_sort":{"id":8769,"name":"silverstripe_sort","label":"silverstripe_sort","description":"","help":"","class":"","type":"text","weight":10,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""}},"show_in_menu":"1","label_singular":"Artwork","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"artwork","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_translation_priority":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"custom","rest_enable":"1","read_all":"0","write_all":"0","built_in_taxonomies_photographer":"0","pfat_filter_archive_custom":"the_content"},"80":{"id":80,"name":"media","label":"Media","description":"","type":"media","storage":"meta","object":"media","alias":"","fields":{"copyright":{"id":84,"name":"copyright","label":"Copyright","description":"","help":"","class":"","type":"paragraph","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","paragraph_allow_html":"1","paragraph_oembed":"0","paragraph_wptexturize":"1","paragraph_convert_chars":"1","paragraph_wpautop":"1","paragraph_allow_shortcode":"0","paragraph_allowed_html_tags":"strong em a ul ol li b i","paragraph_max_length":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","paragraph_repeatable":"0","paragraph_placeholder":""},"photographer":{"id":85,"name":"photographer","label":"Photographer","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"taxonomy","pick_val":"photographer","sister_id":"","required":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"add_current_year":{"id":309,"name":"add_current_year","label":"Add Current Year","description":"","help":"","class":"","type":"boolean","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"boolean_format_type":"checkbox","boolean_yes_label":"Yes","boolean_no_label":"No","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0"},"artwork":{"id":6150,"name":"artwork","label":"Artwork","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"post_type","pick_val":"artwork","sister_id":"8646","required":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"silverstripe_artwork_id":{"id":6151,"name":"silverstripe_artwork_id","label":"silverstripe_artwork_id","description":"","help":"","class":"","type":"text","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"silverstripe_sort":{"id":8772,"name":"silverstripe_sort","label":"silverstripe_sort","description":"","help":"","class":"","type":"number","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","number_format_type":"number","number_format":"i18n","number_decimals":"0","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","number_repeatable":"0","number_placeholder":""}},"show_in_menu":1,"rest_enable":"1","read_all":"0","write_all":"0"},"81":{"id":81,"name":"photographer","label":"Photographers","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":{"firstname":{"id":82,"name":"firstname","label":"Firstname","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"lastname":{"id":88,"name":"lastname","label":"Lastname","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""}},"show_in_menu":"1","label_singular":"Photographer","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"photographer","query_var":"0","sort":"0","built_in_post_types_artist":"0","built_in_post_types_artwork":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_exhibitions":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_attachment":"0","menu_location":"settings","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","menu_location_custom":"media"}}}
```

**Comment by sc0ttkclark** [comment]
How did you include WordPress or call the function? Just want to make sure we can get a better picture of why the class isn't loading.

**Comment by marioschubert** [comment]
I'm not sure, if its related, but I get the same error message. Its triggered, when I update a pods entry. Additionally the files linked in the pod are deleted. :-o


```
2021/02/21 14:53:52 [error] 27182#27182: *12320441 FastCGI sent in stderr: "PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'spp_cfg_metabox_save' not found or invalid function name in /var/www/example.com/wp-includes/class-wp-hook.php on line 289" while reading response header from upstream, client: 62.216.207.56, server: example.com, request: "POST /wp-json/wp/v2/exhibition/41762?_locale=user HTTP/1.1", upstream: "fastcgi://unix:/var/run/example.com-fpm.sock:", host: "example.com", referrer: "https://example.com/wp-admin/post.php?post=41762&action=edit"
2021/02/21 14:53:54 [error] 27182#27182: *12320441 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'PodsMeta' not found in /var/www/example.com/wp-content/plugins/pods/classes/PodsInit.php:2031
Stack trace:
#0 /var/www/example.com/wp-includes/class-wp-hook.php(289): PodsInit->delete_attachment()
#1 /var/www/example.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 /var/www/example.com/wp-includes/plugin.php(484): WP_Hook->do_action()
#3 /var/www/example.com/wp-includes/post.php(5940): do_action()
#4 /var/www/example.com/wp-includes/post.php(3010): wp_delete_attachment()
#5 /var/www/example.com/wp-content/plugins/simple-podcast-press/spp.php(2134): wp_delete_post()
#6 /var/www/example.com/wp-content/plugins/simple-podcast-press/spp.php(125): wp_simplepodcastpress->remove_duplicate_images()
#7 /var/www/example.com/wp-content/plugins/simple-podcast-press/simple-podcast-press.php(85): wp_simplepodcastpress->__construct()
#8 /var/www/example.com/wp-settings.php(388): include_once('/var/www/" while reading response header from upstream, client: 62.216.207.56, server: example.com, request: "GET /wp-admin/post.php?post=41762&action=edit&lang=de&message=4 HTTP/1.1", upstream: "fastcgi://unix:/var/run/example.com-fpm.sock:", host: "example.com", referrer: "https://example.com/wp-admin/post.php?post=41762&action=edit"
```

**Comment by JoryHogeveen** [comment]
@sc0ttkclark What is changed in 2.8 in relation to this issue? `PodsInit::delete_attachment` uses static properties from `PodsMeta`.

Looking at the `run` method in `PodsInit` I see a possibility where this issue can occur.
PodsInit only loads PodsMeta _after_ the `setup_theme` hook, but `delete_attachment` gets hooked directly. So if `delete_attachment` gets called before running `setup_theme` this issue will still occur in Pods 2.8.

Load PodsMeta:
https://github.com/pods-framework/pods/blob/2.8.0/classes/PodsInit.php#L2400-L2404

Delete attachment:
https://github.com/pods-framework/pods/blob/2.8.0/classes/PodsInit.php#L2436

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Okidoki, I assume we can close this topic then?
