### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Tribe\Service_Providers\Shortcodes::filter_do_shortcode_tag()

### ISSUE THREAD

**Issue by gdnwebmedia** [pods-framework/pods#6438]
### Description

Thanks for the great work with Pods! 

The only change I made was installing Oxygen builder 4.0.2 Alpha. I originally thought it was a problem with their installation but then I found a possible solution on the Pods code itself.

This is the full error message:

`[Fatal error: Uncaught ArgumentCountError: Too few arguments to function Tribe\Service_Providers\Shortcodes::filter_do_shortcode_tag(), 2 passed in /home/[DOMAIN-NAME]/srdwszzbts/public_html/wp-includes/class-wp-hook.php on line 307 and exactly 4 expected in /home/[DOMAIN-NAME]/srdwszzbts/public_html/wp-content/plugins/pods/tribe-common/src/Tribe/Service_Providers/Shortcodes.php:118 Stack trace: #0 /home/[DOMAIN-NAME]/srdwszzbts/public_html/wp-includes/class-wp-hook.php(307): Tribe\Service_Providers\Shortcodes->filter_do_shortcode_tag() #1 /home/[DOMAIN-NAME]/srdwszzbts/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters() #2 /home/[DOMAIN-NAME]/srdwszzbts/public_html/wp-content/plugins/oxygen/component-framework/includes/templates.php(66): apply_filters() #3 /home/[DOMAIN-NAME]/srdwszzbts/public_html/wp-content/plugins/oxygen/component-framework/components/classes/link-wrapper.class.php(74): do_oxygen_elements() #4 in /home/[DOMAIN-NAME]/srdwszzbts/public_html/wp-content/plugins/pods/tribe-common/src/Tribe/Service_Providers/Shortcodes.php on line 118]`

### Version

2.8.10

### Testing Instructions

1) I installed Oxygen Builder 4.0.2 Alpha
2) Cleared cache and shortcodes
3) wp-admin was working fine...
4) when tried to go to any page in the front end, I see the error

### Possible Workaround

I went to /wp-content/plugins/pods/tribe-common/src/Tribe/Service_Providers/Shortcodes.php on line 118

located line 118:

`	public function filter_do_shortcode_tag( $output, $tag, $attr, $m ) {
		return $this->container->make( Manager::class )->filter_do_shortcode_tag( $output, $tag, $attr, $m );
	}
`

and changed it to:

`
	public function filter_do_shortcode_tag( $output = NULL, $tag = NULL, $attr = NULL, $m = NULL ) {
		return $this->container->make( Manager::class )->filter_do_shortcode_tag( $output, $tag, $attr, $m );
	}
`

that temporarily solved the problem. 

### Site Health Information

```text
`
### wp-core ###

version: 5.9
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/[domain-name]/srdwszzbts/public_html
wordpress_size: 47.52 MB (49823482 bytes)
uploads_path: /home/[domain-name]/srdwszzbts/public_html/wp-content/uploads
uploads_size: 77.02 MB (80764551 bytes)
themes_path: /home/[domain-name]/srdwszzbts/public_html/wp-content/themes
themes_size: 3.92 MB (4114189 bytes)
plugins_path: /home/[domain-name]/srdwszzbts/public_html/wp-content/plugins
plugins_size: 217.56 MB (228129405 bytes)
database_size: 15.95 MB (16728064 bytes)
total_size: 361.98 MB (379559691 bytes)

### wp-active-theme ###

name: Twenty Twenty-Two (twentytwentytwo)
version: 1.0
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, menus, title-tag
theme_path: fake
auto_update: Disabled

### wp-mu-plugins (2) ###

ManageWP - Worker Loader: author: Webmaster, version: (undefined)
WPMU DEV Hosting: version: 0.1, author: WPMU DEV

### wp-plugins-active (21) ###

Admin Columns Pro: version: 5.6.4, author: AdminColumns.com, Auto-updates disabled
Admin Columns Pro - Pods: version: 1.6.1, author: AdminColumns.com, Auto-updates disabled
Advanced Scripts: version: 2.3.3, author: Clean Plugins, Auto-updates disabled
Automatic.css: version: 1.0.5, author: Kevin Geary, Matteo Greco, Auto-updates disabled
Beehive Pro: version: 3.3.12, author: WPMU DEV, Auto-updates disabled
Branda Pro: version: 3.4.6, author: WPMU DEV, Auto-updates disabled
Defender Pro: version: 2.7.1, author: WPMU DEV, Auto-updates disabled
Forminator Pro: version: 1.15.10, author: WPMU DEV, Auto-updates disabled
HappyFiles Pro: version: 1.6, author: Codeer, Auto-updates disabled
Hustle Pro: version: 4.4.11, author: WPMU DEV, Auto-updates disabled
MalCare Security - Free Malware Scanner, Protection & Security for WordPress: version: 4.72, author: MalCare Security, Auto-updates disabled
ManageWP - Worker: version: 4.9.13, author: Webmaster, Auto-updates disabled
MemberPress Plus: version: 1.9.28, author: Caseproof, LLC, Auto-updates disabled
OxyExtras: version: 1.4.0, author: OxyExtras, Auto-updates disabled
Oxygen 4.0 Alpha 2: version: 4.0 Alpha 2, author: Soflyy, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.8.10, author: Pods Framework Team, Auto-updates disabled
Pods Pro - Page Builder Toolkit Add-On: version: 1.0.5, author: SKC Development, LLC, Auto-updates disabled
SmartCrawl Pro: version: 2.17.1, author: WPMU DEV, Auto-updates disabled
Smush Pro: version: 3.9.5, author: WPMU DEV, Auto-updates disabled
User Role Editor: version: 4.61.1, author: Vladimir Garagulya, Auto-updates disabled
WPMU DEV Dashboard: version: 4.11.8, author: WPMU DEV, Auto-updates enabled

### wp-plugins-inactive (4) ###

Hummingbird Pro: version: 3.3.0, author: WPMU DEV, Auto-updates disabled
Hydrogen Pack: version: 1.3.9, author: Clean Plugins, Auto-updates disabled
Swiss Knife: version: 2.0.6, author: dPlugins, Auto-updates disabled
WP Adminify Pro: version: 2.0.0, author: Jewel Theme, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 15M
upload_max_filesize: 15M
max_effective_size: 15 MB
max_file_uploads: 20
imagick_limits:
imagick::RESOURCETYPE_AREA: 31 GB
imagick::RESOURCETYPE_DISK: 1.844674407371E+19
imagick::RESOURCETYPE_FILE: 768
imagick::RESOURCETYPE_MAP: 31 GB
imagick::RESOURCETYPE_MEMORY: 16 GB
imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.9.0-15-amd64 x86_64
httpd_software: Apache/2.4.25 (Debian)
php_version: 7.4.27 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 899
memory_limit: 2047M
max_input_time: 299
upload_max_filesize: 15M
php_post_max_size: 15M
curl_version: 7.52.1 OpenSSL/1.0.2u
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.20-MariaDB-1:10.4.20+maria~stretch-log
client_version: mysqlnd 7.4.27
max_allowed_packet: 1073741824
max_connections: 29538

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/[domain-name]/srdwszzbts/public_html/wp-content
WP_PLUGIN_DIR: /home/[domain-name]/srdwszzbts/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 2047M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache/2.4.25 (Debian)
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
pods-session-save-path: /var/lib/php/sessions
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Yes
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: Yes
pods-object-cache-apcu: Yes
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: Yes
pods-memory-current-usage: 110.253M
pods-memory-current-usage-real: 10.000M
pods-network-wide: No
pods-install-location: /wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Disable sessions
pods-can-use-sessions: Yes
pods-relationship-table-status: 0

`
```

**Comment by sc0ttkclark** [comment]
Workaround added via https://github.com/pods-framework/pods/commit/66b3bed23466c1e8beb6a01ed1421ed81e025a71

Will be included in Pods 2.8.11 when it goes out.

Going to report this to the Tribe Common repo as well but this does look like an Oxygen compatibility issue specifically.

**Comment by sc0ttkclark** [comment]
To be addressed by the Oxygen team, hopefully they don't release 4.0 without solving this.

https://github.com/soflyy/oxygen-bugs-and-features/issues/2595

**Comment by sc0ttkclark** [comment]
Solve in Oxygen 4.0 Beta 1
