### ISSUE TITLE
Undefined tribe() fatal error

### ISSUE THREAD

**Issue by bartgriffin** [pods-framework/pods#6509]
### Description

My site keeps going down, but only temporarily. I’ve activated debugging. This is what the report keeps showing over and over and over.

`PHP Fatal error Uncaught Error: Call to undefined function tribe() in /var/www/wp-content/plugins/pods/includes/general.php:3251

Stack trace:

#0 /var/www/wp-content/plugins/pods/includes/general.php(3822): pods_get_setting('types_only', '0')
#1 /var/www/wp-content/plugins/pods/src/Pods/Whatsit.php(510): pods_is_types_only()
#2 /var/www/wp-content/plugins/pods/src/Pods/Whatsit.php(277): Pods\Whatsit->setup()
#3 [internal function]: Pods\Whatsit->__wakeup()
#4 /var/www/wp-content/object-cache.php(621): apcu_fetch('45.40.156.50:33...', false)
#5 /var/www/wp-content/object-cache.php(421): GD_APCu_Object_Cache->get('45.40.156.50:33...', 'options', false)
#6 /var/www/wp-includes/option.php(280): wp_cache_get('alloptions', 'options', false)
#7 /var/www/wp-includes/option.php(166): wp_load_alloptions()
#8 /var/www/wp-content/plugins/pods/classes/PodsInit.php(121): get_option('pods_framework_...')
#9 /var/www/wp-content/plugins/pods/classes/PodsInit.php(105): PodsInit->__construct()
#10 /var/www/wp-content/plugins/pods/includes/class in /var/www/wp-content/plugins/pods/includes/general.php on line 3251`

### Version

2.8.16

### Screenshots / Screencast

![Screen Shot 2022-05-09 at 9 04 25 AM](https://user-images.githubusercontent.com/105230983/167450925-968c45d8-bb12-41ab-b226-058b69e3505e.png)

### Site Health Information

```text
`
### wp-core ###

version: 5.9.3
site_language: en_US
user_language: en_US
timezone: Europe/Lisbon
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 7
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www
wordpress_size: loading...
uploads_path: /var/www/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/wp-content/themes
themes_size: loading...
plugins_path: /var/www/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (3) ###

advanced-cache.php: true
db-error.php: true
object-cache.php: true

### wp-active-theme ###

name: Firebreather (hello-elementor-child)
version: 1.0.1580755791
author: Bart Griffin
author_website: https://firebreathergyms.com/
parent_theme: Hello Elementor (hello-elementor)
theme_features: core-block-patterns, widgets-block-editor, menus, post-thumbnails, automatic-feed-links, title-tag, html5, custom-logo, editor-style, align-wide, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: /var/www/wp-content/themes/hello-elementor-child

### wp-parent-theme ###

name: Hello Elementor (hello-elementor)
version: 2.5.0
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
theme_path: /var/www/wp-content/themes/hello-elementor

### wp-themes-inactive (1) ###

Twenty Twenty-Two: version: 1.1, author: the WordPress team

### wp-mu-plugins (2) ###

installatron_hide_status_test.php: author: (undefined), version: (undefined)
System Plugin: author: (undefined), version: 4.23.4

### wp-plugins-active (28) ###

Admin Columns: version: 4.4.5, author: AdminColumns.com
Admin Menu Editor: version: 1.10.1, author: Janis Elsts
Default featured image: version: 1.7.1, author: Jan Willem Oostendorp
Disable Gutenberg: version: 2.6, author: Jeff Starr
Duplicate Post Page Menu & Custom Post Type: version: 2.1.0, author: Inqsys Technology
Ele Custom Skin: version: 3.1.5, author: Dudaster.com
Ele Custom Skin Pro: version: 3.2.3, author: Dudaster.com
Elementor: version: 3.6.5, author: Elementor.com
Elementor Pro: version: 3.6.5, author: Elementor.com
Elementor White Label Branding: version: 1.0.2, author: Ozan Canakli
FV Clone Screen Options: author: (undefined), version: 0.4
Hummingbird Pro: version: 3.3.2, author: WPMU DEV
JetMenu: version: 2.1.7, author: Crocoblock
Limit Login Attempts Reloaded: version: 2.25.1, author: Limit Login Attempts Reloaded
Members: version: 3.2.1, author: MemberPress
Pods - Custom Content Types and Fields: version: 2.8.16, author: Pods Framework Team
Scheduled Post Guardian: version: 1.1.3, author: Mark Jaquith
Simple Custom Post Order: version: 2.5.6, author: Colorlib
Smush Pro: version: 3.9.9, author: WPMU DEV
Sucuri Security - Auditing, Malware Scanner and Hardening: version: 1.8.30, author: Sucuri Inc.
Ultimate Addons for Elementor: version: 1.36.6, author: Brainstorm Force
White Label CMS: version: 2.2.9, author: www.videousermanuals.com
WP Debugging: version: 2.11.9, author: Andy Fragen
WPMU DEV Dashboard: version: 4.11.12, author: WPMU DEV
WP Post Expires: version: 1.2.5, author: XNicON
WP Rocket: version: 3.11.2, author: WP Media
WX Form Management: version: 1.6.19, author: WebConnex
Yoast SEO: version: 18.8, author: Team Yoast

### wp-plugins-inactive (3) ###

Debug Bar: version: 1.1.3, author: wordpressdotorg
Query Monitor: version: 3.9.0, author: John Blackbourn
WP-Optimize - Clean, Compress, Cache: version: 3.2.3, author: David Anderson, Ruhani Rabin, Team Updraft

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-16 Q16-HDRI x86_64 2021-11-21 https://imagemagick.org
imagick_version: 3.4.4
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 100M
max_effective_size: 100 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 251 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 196608
	imagick::RESOURCETYPE_MAP: 251 GB
	imagick::RESOURCETYPE_MEMORY: 126 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVIF, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FARBFELD, FAX, FF, FILE, FITS, FL32, FLV, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HEIF, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, KERNEL, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RSVG, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YAML, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP
ghostscript_version: 9.55.0

### wp-server ###

server_architecture: Linux 5.4.155-200.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.29 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 300
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 100M
php_post_max_size: 100M
curl_version: 7.80.0 OpenSSL/1.1.1n
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.26-29-log
client_version: mysqlnd 7.4.29
max_allowed_packet: 16777216
max_connections: 1000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/wp-content
WP_PLUGIN_DIR: /var/www/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
pods-session-save-path: undefined
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: Yes
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 26.799M
pods-memory-current-usage-real: 8.000M
pods-network-wide: No
pods-install-location: /wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Disable sessions
pods-can-use-sessions: No
pods-relationship-table-status: 132

`
```

**Comment by vosykapavel** [comment]
@bartgriffin I had same error with 2.8.15. With version 2.8.17 it is OK, for me.
