### ISSUE TITLE
Fatal error after update to version 2.9.0

### ISSUE THREAD

**Issue by sylletka** [pods-framework/pods#6581]
### Description

after updating to version 2.9.0 the site is not working anymore, and a fatal error is generated by the pods plugin
the php error log says:
```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: ftp_nlist(): Argument #1 ($ftp) must be of type FTP\Connection, null given in /var/www/wp-admin/includes/class-wp-filesystem-ftpext.php:420

Stack trace:
#0 /var/www/wp-admin/includes/class-wp-filesystem-ftpext.php(420): ftp_nlist()
#1 /var/www/wp-content/plugins/pods/src/Pods/Config_Handler.php(394): WP_Filesystem_FTPext->exists()
#2 /var/www/wp-content/plugins/pods/src/Pods/Config_Handler.php(354): Pods\Config_Handler->load_config_file()
#3 /var/www/wp-content/plugins/pods/src/Pods/Config_Handler.php(137): Pods\Config_Handler->load_configs()
#4 /var/www/wp-content/plugins/pods/classes/PodsInit.php(1205): Pods\Config_Handler->setup()
#5 /var/www/wp-content/plugins/pods/classes/PodsInit.php(820): PodsInit->register_pods()
#6 /var/www/wp-includes/class-wp-hook.php(307): PodsIn" while reading response header from upstream, client: xx.xx.xx.xx, server: www.xxxxxx, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "www.xxxxxx"
```

PHP version:  8.1.6

### Version

2.9.0

**Comment by JoryHogeveen** [comment]
Hi @sylletka 

Please provide all information the bug report asks for, especially Site Health Information.
This sounds like a hosting issue with the filesystem.

**Comment by sc0ttkclark** [comment]
I have a fix for this even though we aren't sure why it's fataling, it's probably not necessary to use WP_Filesystem for read-only file operations.

**Comment by datverse** [comment]
#6242 please preview this closed issue
