### ISSUE TITLE
Fix FieldInspectorControls test failure for RichText field in jest tests

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#6899]
### Description

JS test suite fails for blocks when dealing with RichText component. I was unable to figure out why or how to work around that.

```
FAIL ui/js/blocks/src/blocks/components/test/FieldInspectorControls.test.js
  ● FieldInspectorControls › all supported fields render as expected

    TypeError: Cannot read properties of undefined (reading 'filter')

      43 | 		} = allFieldsEditComponentProps;
      44 |
    > 45 | 		const wrapper = mount(
         | 		                ^
      46 | 			<FieldInspectorControls
      47 | 				fields={ fields }
      48 | 				attributes={ attributes }

      at node_modules/@wordpress/block-editor/build/components/rich-text/@wordpress/block-editor/src/components/rich-text/use-format-types.js:53:25
      at mountMemo (node_modules/react-dom/cjs/react-dom.development.js:15846:19)
      at Object.useMemo (node_modules/react-dom/cjs/react-dom.development.js:16219:16)
      at useMemo (node_modules/react/cjs/react.development.js:1532:21)
      at useFormatTypes (node_modules/@wordpress/block-editor/build/components/rich-text/@wordpress/block-editor/src/components/rich-text/use-format-types.js:52:22)
      at RichTextWrapper (node_modules/@wordpress/block-editor/build/components/rich-text/@wordpress/block-editor/src/components/rich-text/index.js:205:6)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:17044:20)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19098:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:2[24](https://github.com/pods-framework/pods/runs/8297245272?check_suite_focus=true#step:5:25)31:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at fn (node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:435:26)
      at node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:351:17
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at wrapAct (node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:350:13)
      at Object.render (node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:421:16)
      at new ReactWrapper (node_modules/enzyme/src/ReactWrapper.js:115:16)
      at mount (node_modules/enzyme/src/mount.js:10:10)
      at Object.<anonymous> (ui/js/blocks/src/blocks/components/test/FieldInspectorControls.test.js:45:19)

  ● FieldInspectorControls › all supported fields render as expected

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["An error occurred while running 'mapSelect': Cannot read properties of null (reading 'getFormatTypes')"],["An error occurred while running 'mapSelect': Cannot read properties of null (reading 'getFormatTypes')"],["Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'filter')]

      58 |  */
      59 | const RenderedField = ( {
    > 60 | 	field,
         | 	^
      61 | 	attributes,
      62 | 	setAttributes,
      63 | } ) => {

      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)", [TypeError: Cannot read properties of undefined (reading 'filter')]],["The above error occurred in the <ForwardRef(RichTextWrapper)> component:·
      at RichTextWrapper (node_modules/@wordpress/block-editor/build/components/rich-text/@wordpress/block-editor/src/components/rich-text/index.js:84:3)
      at RenderedField (ui/js/blocks/src/blocks/components/RenderedField.js:60:2)
          at div
      at node_modules/@wordpress/components/build/panel/@wordpress/components/src/panel/row.js:11:34
          at div
      at FieldInspectorControls (ui/js/blocks/src/blocks/components/FieldInspectorControls.js:20:2)
      at WrapperComponent (node_modules/@wojtekmaj/enzyme-adapter-utils/src/createMountWrapper.jsx:46:[26](https://github.com/pods-framework/pods/runs/8297245272?check_suite_focus=true#step:5:27))·
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries."]

  ● FieldInspectorControls › all supported fields render as expected

    expect(jest.fn()).not.toHaveWarned(expected)

    Expected mock function not to be called but it was called with:
    ["Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.·
    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.·
    Please update the following components: %s", "CalendarMonth, CalendarMonthGrid, DayPicker, DayPickerSingleDateController"],["Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.·
    * Move data fetching code or side effects to componentDidUpdate.
    * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.·
    Please update the following components: %s", "DayPicker, DayPickerSingleDateController"]

      at Object.assertExpectedCalls (node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:[32](https://github.com/pods-framework/pods/runs/8297245272?check_suite_focus=true#step:5:33):4)
```

### Version

2.9.3

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Fixed? I do not see any errors in our tests anymore?

**Comment by sc0ttkclark** [comment]
Uh I'm not sure 🤣 if our JS tests run and don't show errors in the logs then we're good

**Comment by JoryHogeveen** [comment]
Closing then! If something related comes up we'll create a new one.
