### ISSUE TITLE
Error message with wordpress 6.2.2

### ISSUE THREAD

**Issue by Maathiss** [pods-framework/pods#7082]
### Description

Hello, I have an error message when I want to add or modify a Pods in Wordpress 6.2.2, the message is :

 Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in C:\Users\mathi\Local Sites\mwauto\app\public\wp-content\plugins\pods\classes\PodsAdmin.php:1026 Stack trace: #0 C:\Users\mathi\Local Sites\mwauto\app\public\wp-includes\class-wp-hook.php(308): PodsAdmin->admin_setup('') #1 C:\Users\mathi\Local Sites\mwauto\app\public\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #2 C:\Users\mathi\Local Sites\mwauto\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #3 C:\Users\mathi\Local Sites\mwauto\app\public\wp-admin\admin.php(259): do_action('toplevel_page_p...') #4 {main} thrown in C:\Users\mathi\Local Sites\mwauto\app\public\wp-content\plugins\pods\classes\PodsAdmin.php on line 1026

Do you have a solution for me please ? Thanks you :)

### Version

2.9.14

### Testing Instructions

1. Go on Pods Admin
2. Go on Add new pods or modify pods
3. Error message

### Screenshots / Screencast

![Capture d'écran 2023-04-27 150608](https://github.com/pods-framework/pods/assets/135012535/51394bac-9c06-4ff7-ab17-43e701183d0b)

### Site Health Information

```text
`
### wp-core ###

version: 6.2.2
site_language: fr_FR
user_language: fr_FR
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\Users\mathi\Local Sites\mwauto\app\public
wordpress_size: 55,20 Mo (57876859 bytes)
uploads_path: C:\Users\mathi\Local Sites\mwauto\app\public/wp-content/uploads
uploads_size: 18,56 Mo (19466515 bytes)
themes_path: C:\Users\mathi\Local Sites\mwauto\app\public/wp-content/themes
themes_size: 30,05 Mo (31504696 bytes)
plugins_path: C:\Users\mathi\Local Sites\mwauto\app\public/wp-content/plugins
plugins_size: 78,48 Mo (82289306 bytes)
database_size: 21,83 Mo (22888448 bytes)
total_size: 204,11 Mo (214025824 bytes)

### wp-active-theme ###

name: Astra (astra)
version: 4.1.5
author: Brainstorm Force
author_website: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
parent_theme: none
theme_features: core-block-patterns, astra_hooks, widgets-block-editor, align-wide, automatic-feed-links, title-tag, post-thumbnails, starter-content, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, rank-math-breadcrumbs, amp, widgets, menus
theme_path: C:\Users\mathi\Local Sites\mwauto\app\public/wp-content/themes/astra
auto_update: Désactivé

### wp-themes-inactive (4) ###

Hello Elementor: version: 2.7.1, author: L’équipe d’Elementor, Mises à jour auto désactivées
Twenty Twenty-One: version: 1.8, author: L’équipe WordPress, Mises à jour auto désactivées
Twenty Twenty-Three: version: 1.1, author: L’équipe WordPress, Mises à jour auto désactivées
Twenty Twenty-Two: version: 1.4, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-plugins-active (8) ###

CarDealer: version: 3.10, author: Bill Minozzi, Mises à jour auto désactivées
Duplicate Page: version: 4.5.2, author: mndpsingh287, Mises à jour auto désactivées
Elementor: version: 3.13.4, author: Elementor.com, Mises à jour auto désactivées
Elementor Header & Footer Builder: version: 1.6.14, author: Brainstorm Force, Nikhil Chavan, Mises à jour auto désactivées
Meta Box: version: 5.7.1, author: MetaBox.io, Mises à jour auto désactivées
Pods - Custom Content Types and Fields: version: 2.9.14, author: Pods Framework Team, Mises à jour auto désactivées
Starter Templates: version: 3.2.3, author: Brainstorm Force, Mises à jour auto désactivées
WPForms Lite: version: 1.8.1.2, author: WPForms (latest version: 1.8.1.3), Mises à jour auto désactivées

### wp-plugins-inactive (1) ###

WordPress Importer: version: 0.8.1, author: wordpressdotorg, Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Non disponible
imagemagick_version: Non disponible
imagick_version: Non disponible
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 Mo
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: nginx/1.16.0
php_version: 8.1.9 64bit
php_sapi: cgi-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 7.77.0 OpenSSL/1.1.1q
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 8.1.9
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\Users\mathi\Local Sites\mwauto\app\public/wp-content
WP_PLUGIN_DIR: C:\Users\mathi\Local Sites\mwauto\app\public/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: nginx/1.16.0
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
pods-session-save-path: undefined
pods-session-save-path-exists: Non
pods-session-save-path-writable: Non
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Non
pods-opcode-cache-memcached: Non
pods-opcode-cache-opcache: Oui
pods-opcode-cache-redis: Non
pods-object-cache-apc: Non
pods-object-cache-apcu: Non
pods-object-cache-memcache: Non
pods-object-cache-memcached: Non
pods-object-cache-redis: Non
pods-memory-current-usage: 21,639M / 40M
pods-memory-current-usage-real: 24,000M
pods-network-wide: Non
pods-install-location: C:\Users\mathi\Local Sites\mwauto\app\public\wp-content\plugins\pods/
pods-developer: Non
pods-tableless-mode: Non
pods-relationship-table-enabled: Oui
pods-relationship-table-status: 0
pods-light-mode: Non
pods-strict: Non
pods-allow-deprecated: Oui
pods-api-cache: Oui
pods-shortcode-allow-evaluate-tags: Non
pods-sessions: Désactiver les sessions
pods-can-use-sessions: Non
pods-settings-types_only: Non
pods-settings-watch_changed_fields: Non
pods-settings-metadata_integration: Oui
pods-settings-metadata_override_get: Non

### wpforms ###

version: 1.8.1.2
lite: Mai 24, 2023 @ 2:10 
upload_dir: Accessible en écriture
total_forms: 4
total_submissions: 1

`
```

### Pods Package

```json
I don't have that
```

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/releases/tag/2.9.15

You may also want to run the Pods Admin > Tools > Repair tool on all of your Pods to ensure they are working as expected after you encountered that.
