### ISSUE TITLE
An error of type E_ERROR was caused in line 610 of the file /classes/fields/pick.php

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#7099]
### Description

Reference: https://wordpress.org/support/topic/an-error-of-type-e/

PHP version 8.1.18 

Error Details 
============= 
```An error of type E_ERROR was caused in line 610 of the file /www/XXX/public/wp-content/plugins/pods/classes/fields/pick.php. Error message: Uncaught Error: Call to a member function is_type_covered() on null in /www/XXX/public/wp-content/plugins/pods/classes/fields/pick.php:610 
Stack trace: 
#0 /www/XXX/public/wp-content/plugins/pods/classes/fields/pick.php(866): PodsField_Pick->setup_related_objects() 
#1 /www/XXX/public/wp-content/plugins/pods/classes/PodsForm.php(1558): PodsField_Pick->simple_objects() 
#2 /www/XXX/public/wp-content/plugins/pods/classes/PodsForm.php(1981): PodsForm::field_method('pick', 'simple_objects') 
#3 /www/XXX/public/wp-content/plugins/pods/classes/Pods.php(720): PodsForm::simple_tableless_objects() 
#4 /www/XXX/public/wp-content/plugins/XXX/src/XXXAdmin.php(56): Pods->field('gravity_forms_v...') 
#5 /www/XXX/public/wp-content/plugins/XXX/includes/gf.php(23): XXX\XXXAdmin->getQuestions() 
#6 /www/XXX/public/wp-includes/class-wp-hook.php(308): XXX_gf_init('') 
#7 /www/XXX/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) 
#8 /www/XXX/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#9 /www/XXX/public/wp-settings.php(623): do_action('init') 
#10 /www/XXX/public/wp-config.php(81): require_once('/www/XXX...') 
#11 /www/XXX/public/wp-load.php(50): require_once('/www/XXX...') 
#12 /www/XXX/public/wp-admin/admin.php(34): require_once('/www/XXX...') 
#13 /www/XXX/public/wp-admin/network/admin.php(13): require_once('/www/XXX...') 
#14 /www/XXX/public/wp-admin/network/index.php(11): require_once('/www/XXX...') 
#15 {main} 
thrown ```

### Version

2.9.16

**Comment by sc0ttkclark** [comment]
Fixed via a4a8f232f404f0ed2265df0f1bb486fe7271a0f8

Though I'm betting this may have been related to the TEC/ET stuff possibly, the class container wasn't returning properly when called.
