### ISSUE TITLE
PHP Fatal error:  Uncaught TEC\\Common\\Exceptions\\Not_Bound_Exception

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#7105]
### Description

The below error occurs since last update on all my sites that also have The Events Calendar installed.

-----------

PHP Fatal error:  Uncaught TEC\\Common\\Exceptions\\Not_Bound_Exception: Error while making Pods\\Service_Provider: class tad_DI52_ServiceProvider not found. in /wp-content/plugins/the-events-calendar/common/src/Common/Contracts/Container.php:27

Stack trace:
#0 /wp-content/plugins/the-events-calendar/common/vendor/vendor-prefixed/lucatume/di52/src/Container.php(453): TEC\\Common\\Contracts\\Container->get()
#1 /wp-content/plugins/the-events-calendar/common/src/Tribe/Container.php(305): TEC\\Common\\lucatume\\DI52\\Container->register()
#2 /wp-content/plugins/pods/classes/PodsInit.php(2679): tribe_register_provider()
#3 /wp-includes/class-wp-hook.php(308): PodsInit->run()
#4 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 ....

### Version

2.9.17

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
https://github.com/the-events-calendar/tribe-common/commit/0073f0025e7f59f7607f1899e258c5d099652870
